name: SignServerStats
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 1.1.0
load: POSTWORLD
main: robske_110\SSS\SignServerStats
author: robske_110

permissions:
 SSS:
  description: "Allows to use all SSS features"
  children:
   SSS.signs:
     description: "Allows to create [SSS] signs and destroy them"
   SSS.servertransfer:
     description: "Allows to click on a SSSign and get transfered to that server."
